googleapis/gapic-generator-php

src/Ast/Expression.php
src/Ast/PhpDoc.php
src/CodeGenerator.php
src/Collections/Equality.php
src/Collections/EqualityHelper.php
src/Collections/Map.php
src/Collections/Set.php
src/Collections/Vector.php
src/Main.php
src/Utils/ProtoCatalog.php
src/Utils/ProtoHelpers.php
tests/Ast/ASTTest.php
tests/Ast/PhpDocTest.php
tests/Collections/MapTest.php
tests/Collections/SetTest.php
tests/Collections/VectorTest.php

Place 'strict_types' declaration on its own line; and remove all leading backslashes in 'use' statements.

Fix formatting in all files

---

composer.json
src/Ast/AST.php
src/Ast/HasPhpDoc.php
src/Ast/PhpClass.php
src/Ast/PhpClassMember.php
src/Ast/PhpConstant.php
src/Ast/PhpDoc.php
src/Ast/PhpFile.php
src/CodeGenerator.php
src/Collections/Set.php
src/Generation/GapicClientGenerator.php
src/Generation/ServiceDetails.php
src/Generation/SourceFileContext.php
src/Utils/Formatter.php
src/Utils/ResolvedType.php
src/Utils/Type.php
tests/Ast/PhpDocTest.php
tests/Collections/SetTest.php
tests/ProtoTests/ProtoTest.php
tests/Utils/TypeTest.php

Two reasons for this: (1) Nette contained a bug in handling 'use <trait>' statements; (2) Nette forced code to be converted from AST to text at an earlier stage than desirable. Therefore our custom AST has been expanded to cover the 'structural' PHP previously handled by Nette.

Remove Nette/PhpGenerator dependency

---

src/Ast/AST.php
src/Generation/UnitTestsGenerator.php
tests/ProtoTests/Basic/tests/BasicClientTest.php

An example of a generated PHP test file: https://github.com/googleapis/google-cloud-php/blob/a879c61ac550cc12c501a8a822f6141a78653ff4/Dlp/tests/Unit/V2/DlpServiceClientTest.php

Generate two more test helpers

---

src/Ast/AST.php
src/Ast/Expression.php
src/Generation/GapicClientGenerator.php
tests/ProtoTests/BasicLro/Gapic/BasicLroGapicClient.php

There is an error in the code formatting of some generated comments; this will be fixed in a future PR.
See here for an example of LRO example code in PhpDoc: https://github.com/googleapis/google-cloud-php/blob/e14db65fe40c9dc89fd022496e5c2c63af69a47b/Redis/src/V1/Gapic/CloudRedisGapicClient.php#L601

Add correct LRO example code in PhpDoc

---

src/Generation/FieldDetails.php
src/Generation/GapicClientGenerator.php
src/Utils/Formatter.php
tests/ProtoTests/Basic/Gapic/BasicGapicClient.php
tests/ProtoTests/Basic/RequestWithArgs.php
tests/ProtoTests/Basic/Tests/BasicClientTest.php
tests/ProtoTests/Basic/basic.proto
tests/ProtoTests/Basic/resources/basic_client_config.json
tests/ProtoTests/BasicLro/Gapic/BasicLroGapicClient.php
tests/ProtoTests/BasicLro/Tests/BasicLroClientTest.php

And remove one of the formatting fixers that was causing too many blank lines to be inserted; there is a TODO to understand why this is happening and fix it.

Add proto fields, which become rpc args, to test

---

src/CodeGenerator.php
src/Main.php
src/Utils/ProtoAugmenter.php

PHP is case-insensitive for method/function names, but it's better if they are consistently camelCased :)

Trivial: Fix casings

---

integration_tests/SourceComparer.php
src/Generation/EmptyClientGenerator.php
tests/ProtoTests/Basic/out/src/BasicClient.php
tests/ProtoTests/BasicBidiStreaming/out/src/BasicBidiStreamingClient.php
tests/ProtoTests/BasicClientStreaming/out/src/BasicClientStreamingClient.php
tests/ProtoTests/BasicLro/out/src/BasicLroClient.php
tests/ProtoTests/BasicPaginated/out/src/BasicPaginatedClient.php
tests/ProtoTests/BasicServerStreaming/out/src/BasicServerStreamingClient.php

This fixes the file warning header comment; and allows multiline comments using multiple '//' lines to have their line-breaks in different places

Align the empty client generation with monolith output.

---

tests/ProtoTests/Basic/basic.proto
tests/ProtoTests/Basic/basic_service.yaml
tests/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php

The monolith requires scopes to be defined in the service_config, it ignores scopes defined in the proto

Update basic test to include scopes

---

src/Collections/Vector.php
src/Generation/FieldDetails.php
src/Generation/MethodDetails.php
src/Generation/TestNameValueProducer.php
src/Generation/UnitTestsGenerator.php
src/Utils/Formatter.php
tests/Collections/VectorTest.php
tests/ProtoTests/AllTypes/all-types.proto

Variable-name and test-value generation has been refactored to exactly match monolith.

Refactor unit-test generation to exactly match monolith

---

integration_tests/Invoker.php
integration_tests/Main.php
src/Generation/ResourcesGenerator.php
src/Main.php
src/Utils/GrpcServiceConfig.php
tests/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_client_config.json
tests/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_no_retry_client_config.json

Reproduce the monolith behaviour of using different retry-config generation depending on whether the grpc-service-config is present or not.
This found a real genuine bug! Testing *does* work :)

Enable grpc-service-config on cmd-line; generate correct retrys

---

integration_tests/Main.php
src/Generation/ResourcesGenerator.php
src/Utils/ProtoCatalog.php
tests/ProtoTests/ResourceNames/resource-names.proto
tests/ProtoTests/RoutingHeaders/routing-headers.proto

Dataproc revealed that the monolith has non-deterministic generation for placeholders; hence two integration tests currently removed. Next PR will be to update to latest monolith version which contains the fix; then to re-enable all tests

Fixes required for dataproc; and about to update monolith

---

integration_tests/Main.php
src/Generation/FieldDetails.php
src/Generation/TestNameValueProducer.php
src/Generation/UnitTestsGenerator.php

Handles one-ofs properly for unit-test generation. Correctly fill responses in bidi-streaming unit tests

Add dialogflow integration test, and changes to support it

---

.github/workflows/bazel_example.yml
bazel_example/WORKSPACE.bazel
repositories.bzl
rules_php_gapic/php.bzl
rules_php_gapic/php_repo.bzl
src/Main.php

Update versions of dependencies
Add missing gapic_generator_php_repositories invocation in bazel workspace.
Fix PHP source location, if not using pre-built package.
Fix file copying when performing composer install.
Fix php runner.
Correctly exit generator if EOF (^D) sent to stdin.

Add bazel build test; fix various issues

---

rules_php_gapic/resources/readme.md

Explains how to generate the prebuilt PHP package.
This is copied with some changes from https://github.com/googleapis/gapic-generator/blob/master/rules_gapic/php/resources/README.md

Add readme resources directory

---

bazel_example/BUILD.bazel
bazel_example/example-grpc-service-config.json
integration_tests/Invoker.php
rules_php_gapic/BUILD.bazel
rules_php_gapic/php.bzl
src/CodeGenerator.php
src/Main.php

Allow config-file working directory to be specified on the cmd-line, which i  required when running from bazel.
Return generated files as an array rather than as a generator, to ease debugging.
Update prebuilt PHP to include bcmaths, as required by the proto JSON parser.

Add support for specifying grpc config in bazel

---

bazel_example/BUILD.bazel
bazel_example/example-gapic.yaml
bazel_example/example-service.yaml
bazel_example/example.proto

And update the example to use features of both these config files.
A future PR will ensure the yaml configs are passed through bazel correctly.

Include service and gapic yaml in example

---

bazel_example/WORKSPACE.bazel
rules_php_gapic/php.bzl
rules_php_gapic/php_repo.bzl

Note that this is difficult to test; I've run this locally and in CI
with the pre-built php disabled to ensure that the built-from-sources
version of php works as expected.
Also update example to point to beta01 release of the generator rather than head.
And add comment explaining how php is executed within bazel.

Fix building php from source

---

rules_php_gapic/php.bzl
rules_php_gapic/php_repo.bzl

Copy files, but exclude git and bazel directories, which can cause recursiveness.
Call php without ini file, and with an increased memory limit.

Fix bazel issues

---

.githooks/pre-commit
src/Generation/ResourcesGenerator.php

Running the tests locally for the first time, I got the failure below. This fix prevents such cases from occurring on different machines.
```
1) Google\Generator\Tests\ProtoTests\ProtoTest::testGrpcServiceConfig
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
},\n
"retry_policy_2_params": {\n
"initial_retry_delay_millis": 1000,\n
-                    "retry_delay_multiplier": 1.1,\n
+                    "retry_delay_multiplier": 1.100000023841858,\n
"max_retry_delay_millis": 10000,\n
"initial_rpc_timeout_millis": 11000,\n
"rpc_timeout_multiplier": 1.0,\n
@@ @@
},\n
"retry_policy_3_params": {\n
"initial_retry_delay_millis": 2000,\n
-                    "retry_delay_multiplier": 1.2,\n
+                    "retry_delay_multiplier": 1.2000000476837158,\n …
```

fix(grpc_config): Round retry_delay_multiplier for determinstic tests [ggphp]

---

bazel_example/BUILD.bazel
rules_php_gapic/php_gapic.bzl

Rename 'src' to 'srcs' in bazel php_gapic_library rule

---

integration_tests/Invoker.php
integration_tests/Main.php
src/CodeGenerator.php
src/Generation/ResourcesGenerator.php
src/Generation/ServiceDetails.php
src/Main.php
src/Utils/Helpers.php

Fix file layout of generated code when there are files/namespaces beneath the top-level.
Fix the selection of which resource-name helpers to include in a generated client.
And add adsv6 to the integration test.

Fix generated file layout; fix resource-names

---

tests/Unit/ProtoTests/ProtoTest.php

[ggphp] chore(engx): Lower-case invoked methods in ProtoTest

---

src/Generation/UnitTestsGenerator.php
src/Utils/Formatter.php
tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
tests/Integration/goldens/asset/tests/Unit/V1/AssetServiceClientTest.php
tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
tests/Integration/goldens/redis/tests/Unit/V1/CloudRedisClientTest.php
tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
tests/Integration/goldens/speech/tests/Unit/V1/SpeechClientTest.php
tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
tests/Integration/goldens/videointelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
tests/Unit/ProtoTests/Basic/out/tests/Unit/BasicClientTest.php
tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
tests/Unit/ProtoTests/BasicBidiStreaming/out/tests/Unit/BasicBidiStreamingClientTest.php
tests/Unit/ProtoTests/BasicClientStreaming/out/tests/Unit/BasicClientStreamingClientTest.php
tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
tests/Unit/ProtoTests/BasicLro/out/tests/Unit/BasicLroClientTest.php
tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
tests/Unit/ProtoTests/BasicPaginated/out/tests/Unit/BasicPaginatedClientTest.php
tests/Unit/ProtoTests/BasicServerStreaming/out/tests/Unit/BasicServerStreamingClientTest.php
tests/Unit/ProtoTests/GoldenUpdateMain.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/GrpcServiceConfigWithRetry1Client.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_descriptor_config.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/tests/Unit/GrpcServiceConfigWithRetry1ClientTest.php

It appears that PHP-CS-Fixer treated certain blocks as though there were semicolons at the end, like the snippet below. Running the semicolon fixer after all the other fixers solved this issue.
```
@@ -116,9 +115,9 @@ class BasicClientTest extends GeneratedTest
$this->fail('Expected an ApiException, but no exception was thrown.');
} catch (ApiException $ex) {
$this->assertEquals($status->code, $ex->getCode());
-            $this->assertEquals($expectedExceptionMessage , $ex->getMessage());
-        }
-// Call popReceivedCalls to ensure the stub is exhausted
+            $this->assertEquals($expectedExceptionMessage, $ex->getMessage());
+        };
+        // Call popReceivedCalls to ensure the stub is exhausted
$transport->popReceivedCalls();
$this->assertTrue($transport->isExhausted()); …
```

[ggphp] fix(lint): Add full PSR2 linting rules, fix linter comment un-indentation

---

src/CodeGenerator.php
src/Generation/GapicClientExamplesGenerator.php
src/Generation/TestNameValueProducer.php
src/Generation/UnitTestsGenerator.php
tests/Integration/Main.php

Impacts only a small handful of APIs: `videointelligence`, `speech`, `kms`, `pubsub`, `redis`. Unit tests will differ from the monolith as follows.
```
-----
mono:
$status->details = 'internal error';
$expectedExceptionMessage = json_encode(['message' => 'internal error', 'code' => Code::DATA_LOSS, 'status' => 'DATA_LOSS', 'details' => []], JSON_PRETTY_PRINT);
$operationsTransport->addResponse(null, $status);
// Mock request
$featuresElement = Feature::LABEL_DETECTION;
$features = [$featuresElement];
$inputUri = 'gs://cloud-samples-data/video/cat.mp4';
$response = $client->annotateVideo($features, ['inputUri' => $inputUri]);
$this->assertFalse($response->isDone());
----- 'E' -> '='
micro:
$status->details = 'internal error';
$expectedExceptionMessage = json_encode(['message' => 'internal …
```

[ggphp] fix(mono): Remove sample_code_init_fields usage from test codegen

---

tests/Integration/goldens/container/BUILD.bazel
tests/Integration/goldens/container/src/V1/ClusterManagerClient.php
tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
tests/Integration/goldens/container/src/V1/gapic_metadata.json
tests/Integration/goldens/container/src/V1/resources/cluster_manager_client_config.json
tests/Integration/goldens/container/src/V1/resources/cluster_manager_descriptor_config.php
tests/Integration/goldens/container/src/V1/resources/cluster_manager_rest_client_config.php
tests/Integration/goldens/container/tests/Unit/V1/ClusterManagerClientTest.php

Example: Container and the CancelOperation RPC.

[ggp] fix(client): Generate requestParams descriptor for RPCs with 2+ routing headers

---

src/Generation/GapicClientGenerator.php
tests/Integration/Main.php
tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
tests/Integration/goldens/container/src/V1/Gapic/ClusterManagerGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
tests/Integration/goldens/functions/src/V1/Gapic/CloudFunctionsServiceGapicClient.php
tests/Integration/goldens/iam/src/V1/Gapic/IAMPolicyGapicClient.php
tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
tests/Integration/goldens/logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
tests/Integration/goldens/logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
tests/Integration/goldens/logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php

Fixes request parameter handling bugs compared to the monolith's behavior. Below is the file diff compared to the monolith-produced libraries.
- Container ([PR](https://github.com/googleapis/google-cloud-php/pull/3925))
- WebSecurityScanner ([PR](https://github.com/googleapis/google-cloud-php/pull/3916))
- Language ([PR](https://github.com/googleapis/google-cloud-php/pull/3917))
- BigQueryReservation ([PR](https://github.com/googleapis/google-cloud-php/pull/3918))
**Summary.** Analysis of the headers generated by the monolith for PHP client libraries, potential issues, and proposed fixes in the microgenerator.
**Issue.** The monolith populated request parameters in a manner that does not align with go/aip/4222. Request parameter values were produced based on unclear conditions, which led …

[ggp] fix(client): Handle optional and required request params (phase 2/2)

---

src/Collections/Map.php

This is critical to enabling informative error messages for input proto errors such as duplicate resource definitions.

[ggp] fix: improve Map duplicate-key error message

---

src/Generation/MethodDetails.php

There are no changes to the goldens because `compute_small` does not have this edge case. We can update the version in `googleapis-discovery` and this proto when we finalize on the appropriate pagination heuristic.

fix(regapic): Prefer map over repeated fields for pagination [ggp]

---

src/Generation/MethodDetails.php
tests/Integration/goldens/compute_small/src/V1/Gapic/AddressesGapicClient.php
tests/Integration/goldens/compute_small/src/V1/gapic_metadata.json
tests/Integration/goldens/compute_small/tests/Unit/V1/AddressesClientTest.php

For GCE in conjunction with [the PHP 7 upgrade PR](https://github.com/googleapis/google-cloud-php/pull/3962/files).

fix(regapic): Remove PHP 5 workaround for list_ method renaming [ggp]

---

.github/workflows/phpunit.yml
DEVELOPMENT.md
build_proto.sh
tests/Tools/ProtoLoader.php

The `tools/protoc` binary is not executable on mac os, my guess is because it is a linux binary. So instead of always using that, all scripts/execs default to using `protoc` (local installation in `PATH`) unless `USE_TOOLS_PROTOC` is set.
Also fixes a function that was non-static but called in a static context.

chore: only use tools/protoc if enabled

---

rules_php_gapic/php_repo.bzl

This fixes the use of Linux-only flags on a `cp` command in the Bazel rules. It removes the use of `-s`, which just makes symbolic links of everything instead of copying, removes the use of `--preserve=links` which preserves symbolic links in the source, and changes `-r` to `-R` which should do the same thing as `--preserve=links` in retaining symbolic links.

fix(bazel): fix macos support for bazel build

---

DEVELOPMENT.md
tests/Unit/ProtoTests/GoldenUpdateMain.php
tests/Unit/ProtoTests/UnitGoldenUpdater.php

Adds development instructions on how to update the unit test golden/baseline files, removes two unused variables `GoldenUpdateMain.php`, fixes `UnitGoldenUpdater.php` to create missing baseline directory structure which enables _creation_ of baselines for new test cases not only updates for existing ones.

chore(tests): fix unit golden updater

---

src/Utils/ProtoCatalog.php
tests/Unit/Utils/ProtoHelpersTest.php
tests/Unit/Utils/catalog.proto

This adds a mapping of fully-qualified proto element name to `ServiceDescriptorProto` so that we can look up services by name. This will be useful for DIREGAPIC LRO implementation because a service can name it's Operation service via the `google.cloud.operation_service` method-level annotation. This is just a string value, so we will need to look it up to get the service information.

fix: catalog services in ProtoCatalog

---

src/Utils/GrpcServiceConfig.php
src/Utils/ServiceYamlConfig.php

This just ignores the unknown fields in a JSON/YAML blob when parsing config files. Specifically, the `ServiceYamlConfig.php` doesn't have a `type` field (which it doesn't need), but this field may appear in the YAML files. At some point, the default was changed in `google/protobuf` and in order to upgrade (see #385) we need to explicitly set `ignore_unknown = true`.

fix: enable ignore_unknown in config file parsers

---

src/Generation/UnitTestsGenerator.php
tests/Integration/goldens/compute_small/tests/Unit/V1/AddressesClientTest.php
tests/Unit/ProtoTests/CustomLro/out/tests/Unit/CustomLroClientTest.php

Generated unit tests for the exception case of Custom LRO methods contained an extraneous request message object and its construction. The variable was never used after it was constructed because the test focuses on asserting that an exception happens. The existing LRO exception tests don't use it either. Might want to circle back in a separate PR to clean up that one too.

fix: remove extraneous message in custom lro tests

---

src/Generation/FieldDetails.php
src/Generation/MethodDetails.php
src/Generation/UnitTestsGenerator.php
src/Utils/ProtoHelpers.php
tests/Unit/ProtoTests/CustomLro/custom_lro.proto
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroGapicClient.php
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroOperationsGapicClient.php
tests/Unit/autoload.php

Only those `operation_request_fields` annotated as `REQUIRED` will be honored until further notice.
Also adds a `ProtoHelpers` function for checking `REQUIRED` field_behavior.
Note: compute_small does not have a test for this so I added a non-REQUIRED field to the unit test proto to ensure it was not included.

fix: only expect required request fields on op

---

.github/workflows/bazel_example.yml
.github/workflows/phpunit.yml

I added both branches for a second so that the checks could pass against master before the branch was renamed.
now they can be removed.

chore: remove main branch

---

src/Generation/UnitTestsGenerator.php

Accidentally used plain field `name` which for field names with `_` in them, isn't the proper variable name. Using `camelCase` is the right thing.

fix(diregapic): use camelCase field name in custom op test

---

rules_php_gapic/php_repo.bzl

Ensures that if the PHP binary is rebuilt at build time, the proper options are included, specifically `--with-curl`.

fix(bazel): configure php with curl if rebuilding

---

composer.json
src/Generation/FieldDetails.php
src/Generation/OneofWrapperGenerator.php
tests/Unit/ProtoTests/BasicOneof/basic-oneof.proto
tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
tests/Unit/ProtoTests/BasicOneof/out/tests/Unit/BasicOneofClientTest.php

This is a better fix for #475 than #476, ignoring the synthetic `oneof` at the FieldDetails level rather than everywhere the field is checked as a `oneof`.
Also allow use of PHP 8.x with the generator.

fix: better fix for ignoring required synthetic oneofs

---

rules_php_gapic/php_gapic.bzl

Support supplying a different `gapic-generator-php` binary to the `php_gapic_library` target. This is a mirror of what [C# did](https://github.com/googleapis/gapic-generator-csharp/pull/480) to support their major version rollout.
For http://b/239612041.

fix(bazel): support changing the generator

---

bazel_example/BUILD.bazel
rules_php_gapic/php_gapic.bzl
src/CodeGenerator.php
src/Generation/ResourcesGenerator.php
src/Main.php
tests/Tools/GeneratorUtils.php
tests/Unit/ProtoTests/Basic/out/src/resources/basic_rest_client_config.php
tests/Unit/ProtoTests/BasicBidiStreaming/out/src/resources/basic_bidi_streaming_rest_client_config.php
tests/Unit/ProtoTests/BasicClientStreaming/out/src/resources/basic_client_streaming_rest_client_config.php
tests/Unit/ProtoTests/BasicDiregapic/out/src/resources/library_service_rest_client_config.php
tests/Unit/ProtoTests/BasicLro/out/src/resources/basic_lro_rest_client_config.php
tests/Unit/ProtoTests/BasicOneof/out/src/resources/basic_oneof_rest_client_config.php
tests/Unit/ProtoTests/BasicPaginated/out/src/resources/basic_paginated_rest_client_config.php
tests/Unit/ProtoTests/BasicServerStreaming/out/src/resources/basic_server_streaming_rest_client_config.php
tests/Unit/ProtoTests/CustomLro/out/src/resources/custom_lro_operations_rest_client_config.php
tests/Unit/ProtoTests/CustomLro/out/src/resources/custom_lro_rest_client_config.php
tests/Unit/ProtoTests/DeprecatedService/out/src/resources/deprecated_service_rest_client_config.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_with_retry1_rest_client_config.php
tests/Unit/ProtoTests/ResourceNames/out/src/resources/resource_names_rest_client_config.php
tests/Unit/ProtoTests/RoutingHeaders/out/src/resources/routing_headers_rest_client_config.php

Adds support for the `rest-numeric-enums` plugin option that enables generation of the `numericEnums` flag in the REST descriptor config supported in https://github.com/googleapis/gax-php/pull/395.

feat: numeric enum option generation

---

src/Collections/Map.php
src/Collections/Vector.php

The mixed type declaration was introduced in PHP 8

fix: continue to support php 7.4

---

composer.json

Update minimum version of gax-php used by the generator (tests) in order to capture new `Call::{RPC}_TYPE` constants necessary for #504.

chore(deps): update min gax-php to 1.16

---

.gitignore
src/Ast/AST.php

Support "codifying" `array` and `Vector` types by wrapping them in the corresponding `AST` expression, just like how primitives are handled. Specifically handle `Map` rather than having it be reported as `object`. Include the type of the element that can't be handled in the exception.
With this change, we no longer need to wrap every `array` or `Vector` in an `AST::array` or convert `vector->toArray()` then wrap it - this is done by the AST. Makes code generation helpers easier to test by not requiring that AST Expressions be passed around between function calls, saving code generation/AST wrapping until necessary.

chore(ast): support array, vector, handle map

---

composer.json

Necessary for #513 which depends on the use of GAX's new API `startAsyncCall`.

chore(deps): update gax to v1.17

---

src/Generation/GapicClientGenerator.php
src/Generation/MethodDetails.php
src/Utils/ProtoHelpers.php
tests/Unit/ProtoTests/Basic/out/src/Gapic/BasicGapicClient.php
tests/Unit/ProtoTests/BasicBidiStreaming/out/src/Gapic/BasicBidiStreamingGapicClient.php
tests/Unit/ProtoTests/BasicClientStreaming/out/src/Gapic/BasicClientStreamingGapicClient.php
tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryServiceGapicClient.php
tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
tests/Unit/ProtoTests/BasicOneof/out/src/Gapic/BasicOneofGapicClient.php
tests/Unit/ProtoTests/BasicPaginated/out/src/Gapic/BasicPaginatedGapicClient.php
tests/Unit/ProtoTests/BasicServerStreaming/out/src/Gapic/BasicServerStreamingGapicClient.php
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroGapicClient.php
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroOperationsGapicClient.php
tests/Unit/ProtoTests/DeprecatedService/out/src/Gapic/DeprecatedServiceGapicClient.php
tests/Unit/ProtoTests/DisableSnippets/out/src/Gapic/DisableSnippetsGapicClient.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
tests/Unit/ProtoTests/ResourceNames/out/src/Gapic/ResourceNamesGapicClient.php
tests/Unit/ProtoTests/RoutingHeaders/out/src/Gapic/RoutingHeadersGapicClient.php

As discussed, this reverts startApiCall in the existing gapic generator. The functionality will be ported over to the "v2" generator. This doesn't update the integration goldens, I am planning to include those in the followup PR to introduce the v2 generator. Please let me know if you'd prefer I add them here, instead (just seemed like it would save a few steps to include them in the other PR).

chore: revert startApiCall in gapic generator

---

.allstar/binary_artifacts.yaml

This will exempt the `tools/protoc` binary used for baseline tests from the allstar check i.e. #550 .

chore(allstar): exempt tools/protoc

---

src/Generation/GapicClientGenerator.php

fix: use camelName for optionalArgs when settings requestParamHeaders

---

src/Generation/ServiceDetails.php
tests/Integration/apis/kms/v1/cloudkms_test_mixins_v1.yaml
tests/Integration/apis/kms/v1/service.proto
tests/Integration/goldens/kms/samples/V1/KeyManagementServiceClient/set_iam_policy.php
tests/Integration/goldens/kms/samples/V1/KeyManagementServiceClient/test_iam_permissions.php
tests/Integration/goldens/kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
tests/Integration/goldens/kms/src/V1/gapic_metadata.json
tests/Integration/goldens/kms/src/V1/resources/key_management_service_client_config.json
tests/Integration/goldens/kms/tests/Unit/V1/KeyManagementServiceClientTest.php

fixes #561
This is the correct way to handle it according to https://google.aip.dev/client-libraries/4234#overriding-a-duplicate-rpc

fix: dupe method names from mixins

---

src/Generation/FieldDetails.php

See https://github.com/googleapis/google-cloud-php/pull/5930
See https://github.com/googleapis/google-cloud-php/pull/5916

fix: required-to-optional for Spanner.CommitRequest

---

src/Collections/Vector.php

For some reason, certain APIs would trigger an integer overflow in `Vector::getHash`, forcing a float type coercion by PHP, which is deprecated, resulting in Deprecated warnings being emitted on stdout, ruining protoc plugin output.
This is a partial fix, because we should probably figure out how to also disable language deprecation warnings (or at least redirect to stderr) in the googleapis.

fix: lower hashing constant to avoid overflow

---

rules_php_gapic/php_gapic_pkg.bzl

Some `php_grpc_library` outputs are empty because the package just has types. This causes an unzipping step in `php_gapic_assembly_pkg` to fail. So instead, let's handle them gracefully, logging the empty zip file.
Ultimately, the `php_grpc_library` targets will be removed as part of http://b/240613804, but for now, let's just be more robust.

fix(bazel): ignore empty zip files during packaging

---

tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php
tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php
tests/Integration/goldens/retail/src/V2alpha/Gapic/CompletionServiceGapicClient.php
tests/Integration/goldens/retail/src/V2alpha/Gapic/ProductServiceGapicClient.php
tests/Integration/goldens/retail/src/V2alpha/Gapic/UserEventServiceGapicClient.php
tests/Integration/goldens/securitycenter/src/V1/Gapic/SecurityCenterGapicClient.php
tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php
tests/Integration/goldens/talent/src/V4beta1/Gapic/JobServiceGapicClient.php
tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryGapicClient.php
tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php
tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php

The deps were updated and something in them changed the way we update whitespace (presumably in `friendsofphp/php-cs-fixer`). These changes are good, so we can just update the fixtures to accomadate the changes.

chore: fix test whitespace

---

rules_php_gapic/php.bzl

Increase PHP memory limit for compute + v2 surface, as the build is currently crashing because it's running out of memory
Should allow builds in https://github.com/googleapis/googleapis/pull/807 to pass!

fix: increase php memory limit

---

src/Generation/ServiceDetails.php
tests/Unit/ProtoTests/ResourceNames/out/samples/ResourceNamesClient/nested_reference_method.php
tests/Unit/ProtoTests/ResourceNames/out/src/Client/BaseClient/ResourceNamesBaseClient.php
tests/Unit/ProtoTests/ResourceNames/out/src/Gapic/ResourceNamesGapicClient.php
tests/Unit/ProtoTests/ResourceNames/out/src/gapic_metadata.json
tests/Unit/ProtoTests/ResourceNames/out/src/resources/resource_names_client_config.json
tests/Unit/ProtoTests/ResourceNames/out/src/resources/resource_names_descriptor_config.php
tests/Unit/ProtoTests/ResourceNames/out/src/resources/resource_names_rest_client_config.php
tests/Unit/ProtoTests/ResourceNames/out/tests/Unit/Client/ResourceNamesClientTest.php
tests/Unit/ProtoTests/ResourceNames/out/tests/Unit/ResourceNamesClientTest.php
tests/Unit/ProtoTests/ResourceNames/resource-names.proto

Previously, the algorithm for identifying resources in scope of helper generation only traversed fields of type message that were annotated as required (and of course, represented a resource). This resulted in some such fields being excluded from helper generation, when they are in fact part of the request message tree.
This just removes that check on `isRequired` field, bringing such references in scope.
Updates #453

fix: include non-required resource fields in helpers

---

src/Ast/PhpDoc.php
src/CodeGenerator.php
src/Generation/GapicClientV2Generator.php
tests/Integration/goldens/functions/src/V1/Client/BaseClient/CloudFunctionsServiceBaseClient.php
tests/Integration/goldens/securitycenter/src/V1/Client/BaseClient/SecurityCenterBaseClient.php
tests/Unit/ProtoTests/Basic/out/src/Client/BaseClient/BasicBaseClient.php
tests/Unit/ProtoTests/BasicOneofNew/out/src/Client/BaseClient/BasicOneofNewBaseClient.php
tests/Unit/ProtoTests/RoutingHeaders/out/src/Client/BaseClient/RoutingHeadersBaseClient.php

fixes #547
With phpDocumentor we could remove the prefixed `samples/` by passing in `--examplesdir=samples` when we run `phpdoc`. However, I think including `samples/` in the path is better, since it makes things less ambiguous for anyone looking at the code rather than the published docs.

feat: add phpdoc examples tag

---

src/PostProcessor/FragmentInjectionProcessor.php
src/PostProcessor/ProcessorInterface.php

I missed this the first time around, but all interfaces should be suffixed with `Interface`. This is not an official PHP standard, but it is standard across all the `googleapis` libraries we maintain.

chore: rename processor interface

---

.github/conventional-commit-lint.yaml
src/Generation/FieldDetails.php

Fix BC-breaking changes in https://github.com/googleapis/google-cloud-php/pull/6607
Also organizes array values alphabetically for readability

fix: optional-to-required field for Cloud DMS

---

src/Generation/FieldDetails.php

Reverts googleapis/gapic-generator-php#653 - this was in the wrong place, and also we don't want to make this fix anyway.

Revert "fix: optional-to-required parameter in NetworkConnectivity policy based routing"

---

src/CodeGenerator.php

Prevents duplicate generation of fragments for RPCs that share a request message (not common, but possible).

fix: prevent duplicate fragment gen

---

src/Generation/GapicClientGenerator.php
src/Generation/GapicClientV2Generator.php
tests/Integration/goldens/compute_small/src/V1/Gapic/AddressesGapicClient.php
tests/Integration/goldens/compute_small/src/V1/Gapic/RegionOperationsGapicClient.php
tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryGapicClient.php
tests/Unit/ProtoTests/ClientTest.php
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroGapicClient.php
tests/Unit/ProtoTests/CustomLro/out/src/Gapic/CustomLroOperationsGapicClient.php

Woops! We've been writing the wrong method name all this time. The method is actually `supportedTransports`, but we've been generating `getSupportedTransports`. OH NO!
See [`ClientOptionsTrait::supportedTransports`](https://github.com/googleapis/gax-php/blob/54a863e63ee318308637adb283f6157ccc3aabbb/src/ClientOptionsTrait.php#L284) (called [here](https://github.com/googleapis/gax-php/blob/54a863e63ee318308637adb283f6157ccc3aabbb/src/ClientOptionsTrait.php#L103))

fix: correct method for supportedTransports

---

.gitignore

Add Bazel's `MODULE` file to git ignore. This is due a previous PR having them in the files change by accident, meaning that this could easily happen to any other new member of the team. After a small conversation [here](https://github.com/googleapis/gapic-generator-php/pull/696#pullrequestreview-1958994516), I decided to add them to the `.gitignore`.

chore: Add Bazel's MODULE files to .gitignore

---

src/Generation/FieldDetails.php

See https://github.com/googleapis/google-cloud-php/pull/7118
Recent Bigtable changes have broken BC for the V1 clients because of moving multiple RPC signatures from required to optional. This PR adds patches to revert those changes for the PHP V1 generator.

feat: add patches for bigtable required to optional changes

---

src/Generation/EmulatorSupportGenerator.php
tests/Integration/goldens/spanner/src/V1/Client/DatabaseAdminClient.php
tests/Integration/goldens/spanner/src/V1/resources/database_admin_descriptor_config.php
tests/Integration/goldens/spanner/src/V1/resources/database_admin_rest_client_config.php
tests/Unit/ProtoTests/Basic/out/src/Client/BasicClient.php
tests/scripts/run_bazel_updates.sh

Resolves https://github.com/googleapis/gapic-generator-php/issues/717

fix: Update Emulator configuration function

---

src/Generation/FieldDetails.php

Related:
https://github.com/googleapis/google-cloud-php/pull/7579
Add an fix to the Dialogflow `SearchKnowledgeRequest` by reverting them to optional after the API made a breaking change changing two fields to mandatory when before were optional.

fix: Add two optional to required fields on dialogflow

---

src/Generation/EmulatorSupportGenerator.php

This logic is currently being handled in [RequestHandler](https://github.com/googleapis/google-cloud-php/blob/37844cbfe1f348df180f19648ee18d718e8f9f64/Core/src/RequestHandler.php#L71-L77) for PubSub V2, but for consistency with other GAPICs (and also to encourage users to consume the GAPICs directly), we should support it in the GAPIC clients as well.
TODO: Verify this plays nicely with the current implementation

fix: add emulator support for pubsub clients

---

src/Ast/AST.php
src/Generation/EmulatorSupportGenerator.php
tests/Integration/goldens/spanner/src/V1/Client/DatabaseAdminClient.php
tests/Unit/ProtoTests/Basic/out/src/Client/BasicClient.php

addresses https://github.com/googleapis/google-cloud-php/pull/8053 and https://github.com/googleapis/google-cloud-php/issues/8052

fix: ensure ChannelCredentials class exists
