googleapis/gapic-generator-php

src/Generation/GapicClientGenerator.php, src/Generation/ResolvedType.php, src/Generation/ServiceDetails.php, src/Generation/SourceFileContext.php, src/Generation/Type.php, tests/Generation/TypeTest.php, tests/ProtoTests/ProtoTest.php
And fix a few minor formatted mistakes.
=> Introduce types, generate a little more code; tests

src/Ast/AST.php, src/Ast/HasAccess.php, src/Ast/PhpConstant.php, src/Ast/PhpMethod.php, src/Generation/GapicClientGenerator.php, src/Generation/ServiceDetails.php, src/Utils/Helpers.php, tests/ProtoTests/ProtoTest.php
(There's also a small amount of code for handing method parameters which isn't used in this PR, but will be used in the next PR)
=> Add generation of 'getClientDefaults()' method

src/Generation/EmptyClientGenerator.php, src/Generation/GapicClientGenerator.php, src/Generation/ServiceDetails.php
PRs to follow will test this, and call this as part of the generation process
Also a couple of very minor tidy-ups.
=> Introduce the generator for the empty client class

composer.json, composer.lock, src/Ast/AST.php, src/Ast/PhpDoc.php, src/Ast/PhpParam.php, src/CodeGenerator.php, src/Generation/ServiceDetails.php, src/Generation/UnitTestsGenerator.php, tests/ProtoTests/Basic/tests/BasicClientTest.php
`composer.lock` changes can be ignored - this file is auto-generated (but good practice to commit to the repo)
=> Introduce unit test generation; currently mostly empty

src/Generation/MethodDetails.php, tests/ProtoTests/BasicLro/basiclro.proto, tests/ProtoTests/ProtoTest.php
And introduce the very beginnings of LRO
=> Refactor method-details to allow different method types

src/Generation/GapicClientGenerator.php, src/Generation/MethodDetails.php, tests/ProtoTests/BasicLro/Gapic/BasicLroGapicClient.php
Example here: https://github.com/googleapis/google-cloud-php/blob/e14db65fe40c9dc89fd022496e5c2c63af69a47b/Redis/src/V1/Gapic/CloudRedisGapicClient.php#L461
=> Fix LRO return type in PhpDoc

src/Generation/UnitTestsGenerator.php, tests/ProtoTests/BasicLro/Tests/BasicLroClientTest.php, tests/ProtoTests/ProtoTest.php
These LRO generated tests execute as part of the unit test run, and they pass (although they don't yet test anything)
=> Introduce LRO test cases; currently incomplete

composer.json, integration_tests/Invoker.php, integration_tests/Main.php, integration_tests/SourceComparer.php
Refactor only, no change in functionality
=> Refactor integration test

integration_tests/Main.php, integration_tests/SourceComparer.php, src/CodeGenerator.php, src/Generation/MethodDetails.php, src/Generation/ResourcesGenerator.php, src/Utils/CustomOptions.php, tests/ProtoTests/Basic/out/src/resources/basic_rest_client_config.php, tests/ProtoTests/BasicBidiStreaming/out/src/resources/basic_bidi_streaming_rest_client_config.php, tests/ProtoTests/BasicClientStreaming/out/src/resources/basic_client_streaming_rest_client_config.php, tests/ProtoTests/BasicLro/out/src/resources/basic_lro_rest_client_config.php, tests/ProtoTests/BasicPaginated/out/src/resources/basic_paginated_rest_client_config.php, tests/ProtoTests/BasicServerStreaming/out/src/resources/basic_server_streaming_rest_client_config.php, tests/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_no_retry_rest_client_config.php, tests/ProtoTests/GrpcServiceConfig/out/src/resources/grpc_service_config_rest_client_config.php
The micro-generator is now exactly matching monolith generation for a basic API.
=> Generate REST client config files.

integration_tests/Main.php, src/Ast/AST.php, src/Ast/PhpDoc.php, src/Collections/EqualityHelper.php, src/Collections/Vector.php, src/Generation/GapicClientGenerator.php, src/Generation/MethodDetails.php, src/Generation/ResourceDetails.php, src/Generation/ResourcePart.php, src/Generation/ResourcePatternDetails.php, src/Generation/ServiceDetails.php, src/Utils/ProtoCatalog.php, src/Utils/ProtoHelpers.php, tests/Collections/VectorTest.php, tests/ProtoTests/ResourceNames/resource-names.proto, tests/ProtoTests/ResourceNames/resource-names_gapic.yaml
Including integration test ensuring this micro-generator output exactly matches monolith output.
=> Resource-names initial implementation

integration_tests/Main.php, src/Generation/FieldDetails.php, src/Utils/ProtoAugmenter.php, tests/ProtoTests/ProtoDocs/proto-docs.proto, tests/ProtoTests/ProtoDocs/proto-docs_gapic.yaml
=> Conform proto docs handling between micro and monolith

src/CodeGenerator.php, src/Generation/MethodDetails.php, src/Utils/ProtoHelpers.php
Note that this fix is a pragmatic choice given the code currently doesn't make use of `DescriptorPool`. If this was all to be rewritten from scratch, a different choice may well have been made ;)
=> Fix checking whether a field is a map

integration_tests/Invoker.php, integration_tests/Main.php, src/CodeGenerator.php, src/Generation/ServiceDetails.php, src/Utils/Helpers.php, src/Utils/ProtoAugmenter.php
Changes required in output paths and namespace, as the 'version' part is treated specially.
Change required in doc handling, as some source locations are missing entirely, so handle this gracefully as empty documentation.
=> Test a first real API: language

integration_tests/Main.php, src/Ast/PhpDoc.php, src/Generation/FieldDetails.php, src/Generation/GapicClientExamplesGenerator.php, src/Generation/ResourcesGenerator.php, src/Generation/TestNameValueProducer.php, src/Utils/Formatter.php
Fix minor issues in comments; and ordering of emitted methods
=> Two more real APIs in test.

integration_tests/Main.php, src/Generation/SourceFileContext.php
=> Add channel API to integration test

src/Generation/ResourcesGenerator.php
This should have been in the previous PR, but something went wrong...
=> Very minor refactor

composer.lock, src/Utils/ProtoAugmenter.php
protobuf appears to have a breaking change between 3.13.0 and 3.14.0, so fix affected code.
=> Update PHP deps

integration_tests/Main.php, src/Generation/MethodDetails.php, src/Utils/ServiceYamlConfig.php
And update googleapis to latest, to pull cloud-functions gapic-yaml fix.
And don't require paginated resources field to be field one, as some APIs don't follow the AIP here.
And add a YAML-fixer, as the PHP YAML parser doesn't support multiline string properly
=> Add cloud functions to integration test

.githooks/pre-commit, src/Generation/ResourcesGenerator.php
Re-doing #142, which was reviewed but dropped from the master branch.
=> docs: Add DEVELOPMENT.md [ggphp]

WORKSPACE.bazel, repositories.bzl
`bazel build bazel_example:example_php_proto` within the repo works now.
=> fix(bazel): Fix Bazel build to work within this repo [ggphp]

.github/workflows/bazel_example.yml, src/Generation/ResourcesGenerator.php, tests/Integration/Main.php, tests/Tools/SourceComparer.php
=> [ggphp] fix(mono): Decouple timeouts from service.yaml, bypass timeout_millis in mono_tests

src/CodeGenerator.php, src/Generation/ResourcesGenerator.php, tests/Integration/goldens/logging/src/V2/resources/logging_service_v2_client_config.json
=> [ggphp] feat(resources): handle batching in gapic.yaml

tests/Integration/goldens/dataproc/BUILD.bazel, tests/Integration/goldens/dataproc/src/V1/AutoscalingPolicyServiceClient.php, tests/Integration/goldens/dataproc/src/V1/ClusterControllerClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php, tests/Integration/goldens/dataproc/src/V1/JobControllerClient.php, tests/Integration/goldens/dataproc/src/V1/WorkflowTemplateServiceClient.php, tests/Integration/goldens/dataproc/src/V1/gapic_metadata.json, tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_client_config.json, tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_descriptor_config.php, tests/Integration/goldens/dataproc/src/V1/resources/autoscaling_policy_service_rest_client_config.php, tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_client_config.json, tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_descriptor_config.php, tests/Integration/goldens/dataproc/src/V1/resources/cluster_controller_rest_client_config.php, tests/Integration/goldens/dataproc/src/V1/resources/job_controller_client_config.json, tests/Integration/goldens/dataproc/src/V1/resources/job_controller_descriptor_config.php, tests/Integration/goldens/dataproc/src/V1/resources/job_controller_rest_client_config.php, tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_client_config.json, tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_descriptor_config.php, tests/Integration/goldens/dataproc/src/V1/resources/workflow_template_service_rest_client_config.php, tests/Integration/goldens/dataproc/tests/Unit/V1/AutoscalingPolicyServiceClientTest.php, tests/Integration/goldens/dataproc/tests/Unit/V1/ClusterControllerClientTest.php, tests/Integration/goldens/dataproc/tests/Unit/V1/JobControllerClientTest.php, tests/Integration/goldens/dataproc/tests/Unit/V1/WorkflowTemplateServiceClientTest.php
To serve as a naive baseline in preparation for fixing request parameters.
=> [ggp] fix(tests): Add initial dataproc goldens

tests/Integration/goldens/functions/BUILD.bazel, tests/Integration/goldens/functions/src/V1/CloudFunctionsServiceClient.php, tests/Integration/goldens/functions/src/V1/Gapic/CloudFunctionsServiceGapicClient.php, tests/Integration/goldens/functions/src/V1/gapic_metadata.json, tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_client_config.json, tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_descriptor_config.php, tests/Integration/goldens/functions/src/V1/resources/cloud_functions_service_rest_client_config.php, tests/Integration/goldens/functions/tests/Unit/V1/CloudFunctionsServiceClientTest.php
To serve as a naive baseline for the upcoming request parameter fix.
=> [ggp] fix(tests): Add initial functions goldens

src/Utils/Helpers.php
Handles PubSub's `_deleted-topic_` pattern, which was resulting in invalid code generation.
=> fix: Handle dashes in camelCase string conversion [ggp]

src/Generation/GapicClientGenerator.php
This should have been removed in #293.
=> chore(engx): remove unused param handling code [ggp]

src/Generation/FieldDetails.php
see https://github.com/googleapis/google-cloud-php/pull/5070
=> fix: optional-to-required-parameters for Bigtable

src/Generation/FieldDetails.php
See https://github.com/googleapis/google-cloud-php/pull/4933
=> fix: required-to-optional and optional-to-required parameters for Firestore

src/Generation/EnumConstantGenerator.php, tests/Unit/ProtoTests/BasicDiregapic/library_rest.proto, tests/Unit/ProtoTests/BasicDiregapic/out/src/Enums/TopLevelEnum.php
=> fix: protect against diregapic enum using reserved words

src/Generation/FieldDetails.php
DO NOT MERGE: We need to wait until we can confirm this in the next Spanner update
=> fix: spanner optional-to-required message

src/Generation/OneofWrapperGenerator.php
=> fix: ignore synthetic oneof from proto3_optional

.github/workflows/phpunit.yml, src/Collections/Map.php, src/Collections/Set.php, src/Collections/Vector.php
Fix some type hinting for PHP 8.1 and test with PHP 8.1 in CI.
=> chore: add missing type hints to collections

src/Generation/GapicClientGenerator.php
Removes some dead code that should've been removed in #510.
=> chore: cleanup dead code

DEVELOPMENT.md
=> chore(docs): more dev tips

DEVELOPMENT.md
Added a few missing packages for bazel commands and minor edits in DEVELOPMENT.md.
=> docs: Added a few missing packages for bazel commands

src/Generation/FieldDetails.php
fixes BC issue in https://github.com/googleapis/google-cloud-php/pull/6607
=> fix: ImportMappingRules optional-to-required parameters for DMS

src/Generation/FieldDetails.php
Prevents http://b/300541681 from breaking v1 surface.
=> fix: optional-to-required CreateRepositoryRequest fields

tests/Integration/goldens/asset/src/V1/Gapic/AssetServiceGapicClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/ClusterControllerGapicClient.php, tests/Integration/goldens/dataproc/src/V1/Gapic/JobControllerGapicClient.php, tests/Integration/goldens/redis/src/V1/Gapic/CloudRedisGapicClient.php, tests/Integration/goldens/retail/src/V2alpha/Gapic/CompletionServiceGapicClient.php, tests/Integration/goldens/retail/src/V2alpha/Gapic/ProductServiceGapicClient.php, tests/Integration/goldens/retail/src/V2alpha/Gapic/UserEventServiceGapicClient.php, tests/Integration/goldens/securitycenter/src/V1/Gapic/SecurityCenterGapicClient.php, tests/Integration/goldens/speech/src/V1/Gapic/SpeechGapicClient.php, tests/Integration/goldens/talent/src/V4beta1/Gapic/JobServiceGapicClient.php, tests/Integration/goldens/videointelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php, tests/Unit/ProtoTests/BasicDiregapic/out/src/Gapic/LibraryGapicClient.php, tests/Unit/ProtoTests/BasicLro/out/src/Gapic/BasicLroGapicClient.php, tests/Unit/ProtoTests/GrpcServiceConfig/out/src/Gapic/GrpcServiceConfigWithRetry1GapicClient.php
Spacing in fixtures changed again, need to update them.
=> chore: update fixture spacing

src/Ast/PhpProperty.php, src/Generation/GapicClientV2Generator.php, src/Generation/ServiceDetails.php, src/Utils/CustomOptions.php, tests/Unit/ProtoTests/Basic/basic.proto, tests/Unit/ProtoTests/Basic/out/src/Client/BasicClient.php, tests/Unit/ProtoTests/BasicGrpcOnly/out/src/Client/BasicGrpcOnlyClient.php
Added support for the API version header from the new Versioning header for apis.
=> feat: Add support for the API version header

src/Generation/GapicClientV2Generator.php, src/Utils/ResolvedType.php, tests/Integration/goldens/functions/src/V1/Client/CloudFunctionsServiceClient.php, tests/Integration/goldens/redis/src/V1/Client/CloudRedisClient.php, tests/Integration/goldens/securitycenter/src/V1/Client/SecurityCenterClient.php, tests/Integration/goldens/spanner/src/V1/Client/DatabaseAdminClient.php, tests/Unit/ProtoTests/ResourceNames/out/src/Client/ResourceNamesClient.php
Ensure `parseName` does not use implicit nullable
=> feat: add compatibility for PHP 8.4

.github/workflows/release-checks.yaml
=> feat(ci): add release check for "next release" labels
